# Generated by Django 4.1.5 on 2023-01-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('player_email', models.CharField(max_length=100)),
                ('team_role', models.CharField(max_length=100)),
                ('team_logo', models.ImageField(upload_to='')),
                ('game_name', models.CharField(max_length=100)),
                ('team_code', models.IntegerField(max_length=100)),
            ],
        ),
    ]
