# Generated by Django 4.1.5 on 2023-01-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='team_code',
            field=models.IntegerField(),
        ),
    ]
